// Copyright (C) 2019, Gray Research LLC

`define CFU_INTERFACE_ID	[CFU_INTERFACE_ID_W-1:0]
`define CFU_FUNCTION_ID		[CFU_FUNCTION_ID_W-1:0]
`define CFU_REORDER_ID		[CFU_REORDER_ID_W-1:0]
`define CFU_REQ_RESP_ID		[CFU_REQ_RESP_ID_W-1:0]
`define CFU_REQ_DATA		[CFU_REQ_DATA_W-1:0]
`define CFU_RESP_DATA		[CFU_RESP_DATA_W-1:0]
`define CFU_ERROR_ID		[CFU_ERROR_ID_W-1:0]
