== Specification Change History

=== Version 0.94.240327, 2024-03-27: Add mcx_selector.cte.

Add `mcx_selector.cte`, _custom operation trap enable_.

This enables emulation of absent custom instructions, emulation of
absent composable extensions, and virtualization of stateful composable
extensions state contexts.

=== Version 0.93.240310, 2024-03-10: Revise CX ABI.

Add a CX ABI chapter. Update CX ABI section of Introduction.

The old CX ABI was _callee-save_ management of the CX mux CSRs,
optimizing for minimum CX mux CSR writes.

The new CX ABI is _ambient legacy mode_, maximally paranoid and backwards
compatible, keeping CX muxing _off_ (e.g., selecting for legacy built-in
custom extensions) except when actively issuing CX custom instructions.

=== Version 0.92.231111, 2023-11-11: Add extension multiplexing _version_.

Introduce _CX version, improving CX forward compatibility. Replace
`mcx_selector.en` with `mcx_selector.version`. Add `cx_status.iv` error
field. Replace `cx_status` field names CI/SI/FI with IC/IS/IF.

=== Version 0.91.230803, 2023-08-03: Simplify and improve terminology.

Replace term _Custom Interface (CI)_ with _Composable Extension (CX)_.
Similarly replace _CFU_ with _CXU_.
And so forth.

[width="80%",cols="1,1"]
|===
|From|To

|Custom Interface (CI) |Composable Extension (CX)
|Custom Function Unit (CFU) |Composable Extension Unit (CXU)
|-Zicfu |-Zicx
|`mcfu_*` and `cfu_*` CSRs |`mcx_*` and `cx_*` CSRs
|===

=== Version 0.90.220327, 2022-03-27: First complete draft.
